
dubbo:
  application:
    name: com.sing.dubbo.consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
server:
  port: 8081

weixin:
  appId: wx7b5cacf87cddb94f
  appsecret: 91a30fcffdc8bcf2a210f3f42dc67189
  token: sing1edsawf
  domain: http://rjc78r.natappfree.cc

spring:
  thymeleaf:
    cache: false